In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/BankNoteAuthentication.csv")

In [ ]:
data.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [ ]:
X=data.drop(['class'],axis=1)
y=data['class']

In [ ]:
X.head()

variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [ ]:
tree_classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
predictions=tree_classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [ ]:
print(cm)

[[231   5]
 [  3 173]]


In [ ]:
print(ac)

0.9805825242718447


KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
knn_predict=knn.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_test,knn_predict)
ac=accuracy_score(y_test,knn_predict)

In [ ]:
print(ac)

1.0


In [ ]:
print(cm)

[[236   0]
 [  0 176]]


Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [ ]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [ ]:
print(cm)

[[231   5]
 [  0 176]]


In [ ]:
print(ac)

0.9878640776699029
